---
- hosts: all
  gather_facts: false
  connection: local
  #remote_user: johnhardy
  #sudo: true

  tasks:
    - name: Set remote file path here
      set_fact: remote_file_path=/tmp/file.three    
 
    - name: Create a new file
      file: path="{{ remote_file_path }}" state=touch

    - stat: path="{{ remote_file_path }}"
      register: file_path

    - set_fact: file_content="File Three"

    - copy: content="{{ file_content }}" dest="{{ remote_file_path }}"
      when: file_path.stat.exists == true
